package com.partTi.pojo.recruit;

import com.partTi.pojo.location.Cities;
import com.partTi.pojo.school.School;
import com.partTi.pojo.user.CompanyUser;

import java.io.Serializable;
import java.util.Date;

public class Recruit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.categoryid
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.work_time_type
     *
     * @mbggenerated
     */
    private Integer workTimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.salary
     *
     * @mbggenerated
     */
    private String salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.salary_way
     *
     * @mbggenerated
     */
    private Integer salaryWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.sid
     *
     * @mbggenerated
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.location
     *
     * @mbggenerated
     */
    private Integer location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.state
     *
     * @mbggenerated
     */
    private Integer state;


    private Category category;

    private CompanyUser companyUser;

    private School school;

    private Cities cities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recruit
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.id
     *
     * @return the value of recruit.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.id
     *
     * @param id the value for recruit.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.title
     *
     * @return the value of recruit.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.title
     *
     * @param title the value for recruit.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.detail
     *
     * @return the value of recruit.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.detail
     *
     * @param detail the value for recruit.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.categoryid
     *
     * @return the value of recruit.categoryid
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.categoryid
     *
     * @param categoryId the value for recruit.categoryid
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.start_time
     *
     * @return the value of recruit.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.start_time
     *
     * @param startTime the value for recruit.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.end_time
     *
     * @return the value of recruit.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.end_time
     *
     * @param endTime the value for recruit.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.work_time_type
     *
     * @return the value of recruit.work_time_type
     *
     * @mbggenerated
     */
    public Integer getWorkTimeType() {
        return workTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.work_time_type
     *
     * @param workTimeType the value for recruit.work_time_type
     *
     * @mbggenerated
     */
    public void setWorkTimeType(Integer workTimeType) {
        this.workTimeType = workTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.salary
     *
     * @return the value of recruit.salary
     *
     * @mbggenerated
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.salary
     *
     * @param salary the value for recruit.salary
     *
     * @mbggenerated
     */
    public void setSalary(String salary) {
        this.salary = salary == null ? null : salary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.salary_way
     *
     * @return the value of recruit.salary_way
     *
     * @mbggenerated
     */
    public Integer getSalaryWay() {
        return salaryWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.salary_way
     *
     * @param salaryWay the value for recruit.salary_way
     *
     * @mbggenerated
     */
    public void setSalaryWay(Integer salaryWay) {
        this.salaryWay = salaryWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.num
     *
     * @return the value of recruit.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.num
     *
     * @param num the value for recruit.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.create_time
     *
     * @return the value of recruit.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.create_time
     *
     * @param createTime the value for recruit.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.cid
     *
     * @return the value of recruit.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.cid
     *
     * @param cid the value for recruit.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.sid
     *
     * @return the value of recruit.sid
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.sid
     *
     * @param sid the value for recruit.sid
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.location
     *
     * @return the value of recruit.location
     *
     * @mbggenerated
     */
    public Integer getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.location
     *
     * @param location the value for recruit.location
     *
     * @mbggenerated
     */
    public void setLocation(Integer location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.state
     *
     * @return the value of recruit.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.state
     *
     * @param state the value for recruit.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public CompanyUser getCompanyUser() {
        return companyUser;
    }

    public void setCompanyUser(CompanyUser companyUser) {
        this.companyUser = companyUser;
    }

    public School getSchool() {
        return school;
    }

    public void setSchool(School school) {
        this.school = school;
    }

    public Cities getCities() {
        return cities;
    }

    public void setCities(Cities cities) {
        this.cities = cities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", detail=").append(detail);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", workTimeType=").append(workTimeType);
        sb.append(", salary=").append(salary);
        sb.append(", salaryWay=").append(salaryWay);
        sb.append(", num=").append(num);
        sb.append(", createTime=").append(createTime);
        sb.append(", cid=").append(cid);
        sb.append(", sid=").append(sid);
        sb.append(", location=").append(location);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}