package com.partTi.pojo.recruit;

import com.partTi.pojo.resume.Resume;
import com.partTi.pojo.user.CommonUser;

import java.io.Serializable;
import java.util.Date;

public class WorkResult implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_result.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_result.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_result.recruit_id
     *
     * @mbggenerated
     */
    private String recruitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_result.salary
     *
     * @mbggenerated
     */
    private String salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_result.resume_id
     *
     * @mbggenerated
     */
    private Integer resumeId;


    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_result.state
     *
     * @mbggenerated
     */
    private Integer state;

    private CommonUser commonUser;

    private Recruit recruit;

    private Resume resume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_result
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_result.id
     *
     * @return the value of work_result.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_result.id
     *
     * @param id the value for work_result.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_result.uid
     *
     * @return the value of work_result.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_result.uid
     *
     * @param uid the value for work_result.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_result.recruit_id
     *
     * @return the value of work_result.recruit_id
     *
     * @mbggenerated
     */
    public String getRecruitId() {
        return recruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_result.recruit_id
     *
     * @param recruitId the value for work_result.recruit_id
     *
     * @mbggenerated
     */
    public void setRecruitId(String recruitId) {
        this.recruitId = recruitId == null ? null : recruitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_result.salary
     *
     * @return the value of work_result.salary
     *
     * @mbggenerated
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_result.salary
     *
     * @param salary the value for work_result.salary
     *
     * @mbggenerated
     */
    public void setSalary(String salary) {
        this.salary = salary == null ? null : salary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_result.resume_id
     *
     * @return the value of work_result.resume_id
     *
     * @mbggenerated
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_result.resume_id
     *
     * @param resumeId the value for work_result.resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_result.state
     *
     * @return the value of work_result.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_result.state
     *
     * @param state the value for work_result.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public CommonUser getCommonUser() {
        return commonUser;
    }

    public void setCommonUser(CommonUser commonUser) {
        this.commonUser = commonUser;
    }

    public Recruit getRecruit() {
        return recruit;
    }

    public void setRecruit(Recruit recruit) {
        this.recruit = recruit;
    }

    public Resume getResume() {
        return resume;
    }

    public void setResume(Resume resume) {
        this.resume = resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_result
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        return "WorkResult{" +
                "id=" + id +
                ", uid=" + uid +
                ", recruitId='" + recruitId + '\'' +
                ", salary='" + salary + '\'' +
                ", resumeId=" + resumeId +
                ", createTime=" + createTime +
                ", state=" + state +
                '}';
    }
}