package com.partTi.pojo.school;

import java.io.Serializable;

public class School implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.location
     *
     * @mbggenerated
     */
    private Integer location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.badge_img
     *
     * @mbggenerated
     */
    private String badgeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.id
     *
     * @return the value of school.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.id
     *
     * @param id the value for school.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.name
     *
     * @return the value of school.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.name
     *
     * @param name the value for school.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.detail
     *
     * @return the value of school.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.detail
     *
     * @param detail the value for school.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.location
     *
     * @return the value of school.location
     *
     * @mbggenerated
     */
    public Integer getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.location
     *
     * @param location the value for school.location
     *
     * @mbggenerated
     */
    public void setLocation(Integer location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.badge_img
     *
     * @return the value of school.badge_img
     *
     * @mbggenerated
     */
    public String getBadgeImg() {
        return badgeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.badge_img
     *
     * @param badgeImg the value for school.badge_img
     *
     * @mbggenerated
     */
    public void setBadgeImg(String badgeImg) {
        this.badgeImg = badgeImg == null ? null : badgeImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", detail=").append(detail);
        sb.append(", location=").append(location);
        sb.append(", badgeImg=").append(badgeImg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}